# === Define: brocadevtm::pools
#

define brocadevtm::pools (
  $ensure,
  $basic__bandwidth_class                   = "",
  $basic__failure_pool                      = "",
  $basic__max_connection_attempts           = 0,
  $basic__max_idle_connections_pernode      = 50,
  $basic__max_timed_out_connection_attempts = 2,
  $basic__monitors                          = [],
  $basic__node_close_with_rst               = false,
  $basic__node_connection_attempts          = 3,
  $basic__nodes_table                       = [],
  $basic__note                              = "",
  $basic__passive_monitoring                = true,
  $basic__persistence_class                 = "",
  $basic__transparent                       = false,
  $auto_scaling__cloud_credentials          = "",
  $auto_scaling__cluster                    = "",
  $auto_scaling__data_center                = "",
  $auto_scaling__data_store                 = "",
  $auto_scaling__enabled                    = false,
  $auto_scaling__external                   = true,
  $auto_scaling__hysteresis                 = 20,
  $auto_scaling__imageid                    = "",
  $auto_scaling__ips_to_use                 = "publicips",
  $auto_scaling__last_node_idle_time        = 3600,
  $auto_scaling__max_nodes                  = 4,
  $auto_scaling__min_nodes                  = 1,
  $auto_scaling__name                       = "",
  $auto_scaling__port                       = 80,
  $auto_scaling__refractory                 = 180,
  $auto_scaling__response_time              = 1000,
  $auto_scaling__scale_down_level           = 95,
  $auto_scaling__scale_up_level             = 40,
  $auto_scaling__securitygroupids           = [],
  $auto_scaling__size_id                    = "",
  $auto_scaling__subnetids                  = [],
  $connection__max_connect_time             = 4,
  $connection__max_connections_per_node     = 0,
  $connection__max_queue_size               = 0,
  $connection__max_reply_time               = 30,
  $connection__queue_timeout                = 10,
  $dns_autoscale__enabled                   = false,
  $dns_autoscale__hostnames                 = [],
  $dns_autoscale__port                      = 80,
  $ftp__support_rfc_2428                    = false,
  $http__keepalive                          = true,
  $http__keepalive_non_idempotent           = false,
  $kerberos_protocol_transition__principal  = "",
  $kerberos_protocol_transition__target     = "",
  $load_balancing__algorithm                = "round_robin",
  $load_balancing__priority_enabled         = false,
  $load_balancing__priority_nodes           = 1,
  $node__close_on_death                     = false,
  $node__retry_fail_time                    = 60,
  $smtp__send_starttls                      = true,
  $ssl__client_auth                         = false,
  $ssl__enable                              = false,
  $ssl__enhance                             = false,
  $ssl__send_close_alerts                   = true,
  $ssl__server_name                         = false,
  $ssl__signature_algorithms                = "",
  $ssl__ssl_ciphers                         = "",
  $ssl__ssl_support_ssl2                    = "use_default",
  $ssl__ssl_support_ssl3                    = "use_default",
  $ssl__ssl_support_tls1                    = "use_default",
  $ssl__ssl_support_tls1_1                  = "use_default",
  $ssl__ssl_support_tls1_2                  = "use_default",
  $ssl__strict_verify                       = false,
  $tcp__nagle                               = true,
  $udp__accept_from                         = "dest_only",
  $udp__accept_from_mask                    = "",
){
  include brocadevtm
  $ip   = $brocadevtm::rest_ip
  $port = $brocadevtm::rest_port
  $user = $brocadevtm::rest_user
  $pass = $brocadevtm::rest_pass

  info ("Configuring pools ${name}")
  vtmrest { "pools/${name}":
    endpoint => "https://${ip}:${port}/api/tm/3.3/config/active",
    ensure => $ensure,
    username => $user,
    password => $pass,
    content => template('brocadevtm/pools.erb'),
    type => 'application/json',
    internal => 'pools',
    debug => 0,
  }
}
